// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oradszlwboshvbfjbfgs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yYWRzemx3Ym9zaHZiZmpiZmdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MzQyMzEsImV4cCI6MjA2MTUxMDIzMX0.ixHTpaORdxvKDhqjnNPWyuxJLZb4NfjG_xL_125lhU8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);